### ISSUE TITLE
Object curly spacing?

### ISSUE THREAD

**Issue by timkelty** [kswedberg/eslint-config-kswedberg#1]
I find myself feeling `object-curly-spacing: ['error', 'always']` to look and feel more natural.

Of course I'll defer to your pref, but just thought I'd bring it up. Thoughts?

https://eslint.org/docs/rules/object-curly-spacing

**Comment by kswedberg** [comment]
No.

**Comment by kswedberg** [comment]
jk. as we discussed, let's keep as is for the sake of simplicity
